---
title: "Notes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 1. Intro class 

- More intuition, less coding
- Many models 
- Papers after each part 
- 

#### K-means and PAM

- k-means - abstract point
- PAM - concrete point form dataset

PAM:
1. Find set of points to be medoids
2. assign every point to the closest medoid 
3. For every point (not medoid) check if it would be better medoid
4. If best point is chosen end


#### Distances

Euclidean: Sum of squares of distances
Mannhatan: Sum of absolutes of distances
Minkovski: Generalised version

- Minkovski - when everything's not working, gives "round" results


#### Silhouette 

Is number of clusters right? 

For each observation check if the assgned cluster is the closest one. Silhouette for one observation is difference between my cluster to next-closest cluster. Silhouette for all is the mean. 

Higher the better. Really bad when negative (means that assigned cluster is wrong)


### Class 2
Kmeans goals:

- Run classification
- Test measures
- Predictions


### Class 3 - pre- and post-diagnostics

- Statistics in clustered groups - differences between clusters obtained
- Usually data has features (used in clustering), and extra profiling.
- Example - features: debt, earnings etc. profiling: age, sex etc.

- Distance from cluster center
- Boxplots for variables in groups
- 














